export enum CreationType {
  Manual = 0,
  AutoGenerated = 1,
}

export enum ExerciseTypeSummary {
  MCQ = 0,
  FillBlank = 1,
  Flashcard = 2,
}

export interface PracticeSetExerciseSummary {
  exerciseId: string;
  question: string;
  type: ExerciseTypeSummary;
  orderIndex: number;
}

export interface PracticeSet {
  practiceSetId: string;
  title: string;
  description?: string | null;
  creationType: CreationType;
  lessonId?: string | null;
  lessonTitle?: string | null;
  exercises?: PracticeSetExerciseSummary[] | null;
  exerciseCount: number;
  sessionCount: number;
  createdAt: string;
  updatedAt: string;
}

export interface SavePracticeSetRequest {
  title: string;
  description?: string | null;
  creationType?: CreationType;
}

export interface GeneratePracticeSetRequest {
  title: string;
  description?: string | null;
  tagIds: string[];
}

export interface AddExerciseToSetRequest {
  exerciseId: string;
  orderIndex?: number | null;
}
