namespace LearnBase.API.Models.Enums;

/// <summary>
/// How a Practice Set was created
/// </summary>
public enum CreationType
{
    /// <summary>User manually selected exercises</summary>
    Manual,

    /// <summary>System auto-generated from tag selection</summary>
    AutoGenerated
}